---
- name: Download and install artifactory
  ansible.builtin.apt:
    deb: https://releases.jfrog.io/artifactory/artifactory-pro-debs/pool/jfrog-artifactory-pro/jfrog-artifactory-pro-[RELEASE].deb
- name: Start service artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: true
