---
- name: provision des vm dev
  hosts: all
  become: yes
  vars_files:
  - vars/webapp-env.yml
  tasks:
  - name: apt cache update
    apt:
      update_cache: yes
  - name: install utils
    apt: 
      name: 
      - git
      - vim
      - wget
      - curl
  - name: install java
    apt: 
    - name: 
      - "{{java_package_project}}"
  - name: instal Maven
    include_tasks: tasks/maven.yml
  - name: Clone the github repository usine-logicielle
    git:
      repo: https://github.com/Nuxation/webapp-usine.git
      dest: /home/vagrant/
      clone: yes
      update: yes
