---
- name: Provision des vm dev
  hosts: all
  become: true
  vars_files:
    - vars/webapp-env.yml
  tasks:
    - name: Install cache update, Utilities, java
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - git
          - vim
          - wget
          - "{{ java_package }}"
          - maven

    - name: Clone the github repository usine-logicielle
      ansible.builtin.git:
        repo: https://github.com/Nuxation/webapp-usine.git
        dest: "{{ project_path }}"
        clone: true
        version: "{{ dev_commit }}"
    - name: Build project with maven
      ansible.builtin.shell: mvn clean install
      args:
        chdir: "{{ project_path }}/"
      register: mvn_result
    - name: Build container image
      community.docker.docker_image:
        name: webapp
        build:
          path: "{{ project_path }}/."
        state: present
        source: build
    - name: Build container
      community.docker.docker_container:
        name: server
        detach: true
        ports:
          - 8888:8080
        image: webapp
